### ISSUE TITLE
Update for i386 missing

### ISSUE THREAD

**Issue by Kisty** [home-assistant/plugin-dns#21]
Hi there!

Am trying to update Home Assistant on my netbook but it's having issues updating the core DNS addon. Can you help? Am updating from 2020.12.1 to 2021.1.0 and installed using generic x86 installer. Thanks!

```
21-01-12 20:08:53 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install homeassistant/i386-hassio-dns:None -> 404 Client Error: Not Found ("manifest for homeassistant/i386-hassio-dns:None not found: manifest unknown: manifest unknown").
21-01-12 20:08:53 ERROR (MainThread) [supervisor.plugins.dns] CoreDNS update fails
21-01-12 20:08:53 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<Tasks._update_dns() done, defined at /usr/src/supervisor/supervisor/misc/tasks.py:238> exception=CoreDNSUpdateError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 244, in _update_dns
    await self.sys_plugins.dns.update()
  File "/usr/src/supervisor/supervisor/plugins/dns.py", line 210, in update
    raise CoreDNSUpdateError() from None
supervisor.exceptions.CoreDNSUpdateError
```

**Comment by ludeeus** [comment]
Try this.

```bash
ha su reload
ha su repair
ha dns update
```

**Comment by Kisty** [comment]
Thanks for this, @ludeeus. Fixed this by clearing space in the end. Still having issues with updating supervisor so will give those steps a whirl.
See https://github.com/home-assistant/supervisor/issues/2410

**Comment by ludeeus** [comment]
That is something else, closing this issue and will have a look at the other one :+1:
